### ISSUE TITLE
`cmf init` enforces mandatory options inconsistently

### ISSUE THREAD

**Issue by mpamarques** [criticalmanufacturing/cli#112]
cmf init documentation states the following:

Usage:
  cmf init [options] <projectName> [<rootPackageName> [<workingDir>]]

Arguments:
  <projectName>
  <rootPackageName>    [default: Cmf.Custom.Package]
  <workingDir>         Working Directory [default: .]

However, if I try, for example, the following:

cmf init "MyProject"
I have an error because --customPackageName is mandatory

**Comment by m-s-** [comment]
There is no `customPackageName` argument, there is however a `rootPackageName` argument which is optional (it assumes Cmf.Custom.Package if not present.) The arguments are actually ok, only the `projectName` is required. However, there are several options that generate invalid repositories if not provided. So I'm reusing this issue for that.

Thanks for you report.

**Comment by m-s-** [comment]
Closed by #143
