### ISSUE TITLE
cmf init --force option is not documented

### ISSUE THREAD

**Issue by mpamarques** [criticalmanufacturing/cli#113]
When running cmf init without an output directory, the following error is shown:

"Rerun the command and pass --force to accept and create."

However, documentation does not mention this

**Comment by m-s-** [comment]
There actually isn't a --force option, at all. If you try to use it you'll get an error. The templating library supports forcing but we do not. We could artificially hide that library output, as it does cause some confusion, but unless we kinda find/replace there's nothing to identify it as such.

So, I agree this isn't very user friendly but the documentation is correct.
