### ISSUE TITLE
cmf init generates GlobalVariables.yml without any values defined and there is no documentation about that

### ISSUE THREAD

**Issue by mpamarques** [criticalmanufacturing/cli#116]
Hi,

I'm not sure I did something wrong, but after running cmf init, it generated the GlobalVariables.yml file without the values filled.

Trying to fill them, I searched for documentation on what it means, but I couldn't find anything. There are some fields that are self-explanatory, but I don't know what these mean:

CmfCliRepository (I looked for an example and the value should be 'https://registry.npmjs.com')
CmfPipelineRepository
CmfPipelineVersion

Thank you and best regards.

**Comment by m-s-** [comment]
Hi Miguel,
did you provide the infrastructure file to the `init` command?

**Comment by mpamarques** [comment]
Hi, no, I didn't. If that's what's missing, do you think it is a good idea to update the documentation to mention this?
