### ISSUE TITLE
Local Command to Check Changes Packages

### ISSUE THREAD

**Issue by pedromsilvapt** [criticalmanufacturing/cli#230]
Hi everyone :)

For internal development, it would be useful to have a command we could run on our local machines, or a commit hook that  would run before each commit, and would perform the same validation that our internal PR-Changes pipeline already does.

If any of the sub-packages have changes from the latest published PR, force or notify the userto bump that package's version.

**Comment by m-s-** [comment]
This was prototyped a while ago and I've asked among the Tech Leads if this would be a desired feature but got no feedback. This can easily be included in the development plugin, if there's any interest in it.

**Comment by m-s-** [comment]
Anyway, this is not related to the CLI, but to the development plugin, so I'm closing this issue. Let me know if you want to discuss further.
