### ISSUE TITLE
Add Database Variables group to releases

### ISSUE THREAD

**Issue by m-s-** [criticalmanufacturing/cli#253]
We need the database credentials to drop the databases in the first stages of the releases, however the credentials are encrypted. 
1. Add a new variable group "Database Variables" to the pipelines
2. Add instructions to the documentation on how to create this variable group in the Library

**Comment by joaoopereira** [comment]
implementation decision:
Rename `Docker Variables` to `Authentication Variables`.
This should have the following variables:
 - **Authentication Variables**
 - **DatabaseOnlineUser**
 - **DatabaseOnlinePassword**
 - **DatabaseODSUser**
 - **DatabaseODSPassword**
 - **DatabaseDWHUser**
 - **DatabaseDWHPassword**
