### ISSUE TITLE
`cmf init` should not generate azure devops pipelines by default

### ISSUE THREAD

**Issue by joaoopereira** [criticalmanufacturing/cli#268]
`cmf init` should only generate azure devops pipelines if the following options are provided:
`--azureDevOpsCollectionUrl`, `--agentPool "Releases"`, `--agentType "Hosted"`

**Comment by m-s-** [comment]
This will be moved to a plugin, CLI will no longer generate the pipelines

**Comment by m-s-** [comment]
Closed by #296
