### ISSUE TITLE
refactor: deprecate pipelines scaffolding

### ISSUE THREAD

**Issue by joaoopereira** [criticalmanufacturing/cli#288]
Remove the scaffolding of AzureDevOps pipelines from `cmf init`

Additionally, we should update the cmf-dev plugin to get the `ISOLocation` from the `project-config.json` file instead of `GlobalVariables.yml`

**Comment by joaoopereira** [comment]
closes #255

**Comment by m-s-** [comment]
Tracking this at #288

**Comment by m-s-** [comment]
closed by #298
