### ISSUE TITLE
pack and publish commands should support multiple repos

### ISSUE THREAD

**Issue by joaoopereira** [criticalmanufacturing/cli#29]
Maybe also the publish command

**Comment by m-s-** [comment]
This should be necessary for partners working on top of baselines: for some operations that we will want to support in the future, we will likely need to support the repo with the baseline plus the repo with the MES packages (e.g. the ISO packages)

**Comment by joaoopereira** [comment]
the publish command will be refactored by issue #53, and the pack command will no longer support dependencies packing #54. based on that this issue will be closed.
