### ISSUE TITLE
IoT Package for V10 is generating trash in the Artifact

### ISSUE THREAD

**Issue by jrk94** [criticalmanufacturing/cli#343]
In V10, the html part of the iot package is required only in GUI compile time. The GUI part of IoT is no longer required as part of the iot customization package. The package will only need what is under runtime/ .

The package uses Content to pack to know what it has to pack and to generate the .tgz, but by leveraging content to pack, it also leaves trash in the final .zip

**Comment by m-s-** [comment]
Fixed in #341
