### ISSUE TITLE
`cmf pack` isn't solving the package root for the working directory

### ISSUE THREAD

**Issue by m-s-** [criticalmanufacturing/cli#367]
Every command that works on a specific package should automatically solve the package root from the current directory, so we don't have to move to the package root to run a simple command. If the command works at a repository level, it should solve that location automatically.

`pack` isn't doing that so it needs fixing. We should also review the other commands.

**Comment by ponces** [comment]
Fixed by https://github.com/criticalmanufacturing/cli/pull/411.
