### ISSUE TITLE
Scaffolding HTML solution

### ISSUE THREAD

**Issue by jrk94** [criticalmanufacturing/cli#39]
The first action on the CMF HTML scaffolding should be validate that the path to the html package is correctly mounted 

i.e cmf new html --version 1.0.0 --htmlPackage D:\packages\Cmf.Presentation.HTML.8.2.2.zip
First action should be validate, this exists -> D:\packages\Cmf.Presentation.HTML.8.2.2.zip

**Comment by m-s-** [comment]
This is fixed with #92
