### ISSUE TITLE
Link Dependencies should be automatic

### ISSUE THREAD

**Issue by jrk94** [criticalmanufacturing/cli#65]
Would be great to have a command that will check the dependecies and the project itself and update the GUI package json cmfLinkDependencies to the correct relative paths

**Comment by m-s-** [comment]
I'm holding off on this due to the GUI build process migration, but it's not hard and the migration is still a while off so we can get to this if you find it really needed. It's true devs usually don't link stuff themselves, as the generators do it for them.

**Comment by m-s-** [comment]
This is currently in preview in the development plugin
